services:
    mongodb:
        image: mongo:latest
        container_name: mongodb_uno
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        env_file:
            - .env
